### ISSUE TITLE
Logic Bug

### ISSUE THREAD

**Issue by elibroftw** [brettvanderwerff/ebay-Buy-It-Now-Search-Tool#2]
On line 50, there is a while True loop that with only time.sleep(86400). If you haven't realized by now already, after it sleeps for 24 hours, it's going to sleep for another 24 hours (because it's in an infinite loop), and so on and so forth. You should remove this while True loop and just keep the try and except.

Also: in get_UPC.py, replace lines 13 to 16 with

`if not (user_UPC).isdigit() or len(user_UPC) != 12:
        print('Sorry. UPCs consist of only 12 digits, please look at your input again.')`

**Comment by brettvanderwerff** [comment]
This should be all addressed now. The logic fix actually revealed another issue where the user would be asked for the UPC again every 24 hours, which is now fixed too. Thanks for taking a look at this.
